name: SlackChat
version: 1.0.0
description: Slack chat integration
author: norway240
website: http://norway240.com
main: com.norway240.slack.Slack

commands:
   slackchat:
      description: Reloads config
      usage: /slackchat
      permission: slackchat
      permission-message: You don't have permission

permissions:
    slackchat:
        description: Allows acess to change settings
        default: op