name: SlackChat
version: 1.0.0
description: Slack chat integration
author: norway240
website: http://norway240.com
main: com.norway240.slack.Slack

commands:
   slackchat:
      description: Reloads config
      usage: /slackchat
      permission: slackchat
      permission-message: You don't have permission
   staff:
      description: Displays all mentionable staff via slack
      usage: /staff
      permission: staff
      permission-message: Stupid server admin configured this wrong.

permissions:
    slackchat:
        description: Allows acess to change settings
        default: op
    staff:
        description: Display staff and such.
        default: true